# Generated by Django 5.2.14 on 2026-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_application_unique_together_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'stage'], name='app_job_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate_full_name'], name='app_candidate_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['added_by'], name='app_recruiter_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-created_at'], name='app_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_open', 'job_type'], name='open_jobs_type_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='job_company_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='job_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
    ]
